# Generated by Django 4.0.6 on 2022-08-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-11-05'),
            preserve_default=False,
        ),
    ]
